version: '3'
services:
  base: &base
    image: core_ext
    working_dir: /home/app/app
    volumes:
      - .:/home/app/app

  base_build:
    <<: *base
    build: .
    command: echo done

  core_ext:
    <<: *base
    container_name: core_ext
    depends_on: [base_build]
    command: /bin/bash -c 'rspec'

  test_all:
    <<: *base
    depends_on: [base_build]
    command: /bin/bash -c 'rspec && yard && rake yardstick_measure && rake verify_measurements'

  core_ext_circleci:
    image: darthjee/circleci_ruby_331:1.0.2
    container_name: core_ext_circleci
    command: /bin/bash
    volumes:
      - .:/home/circleci/project
    environment:
      PROJECT: core_ext
