threshold: 100
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude: []
  ReturnTag:
    enabled: true
    exclude:
      - Darthjee::CoreExt::Array::HashBuilder#initialize
      - Darthjee::CoreExt::Hash::ChainFetcher#initialize
      - Darthjee::CoreExt::Hash::KeyChanger#initialize
      - Darthjee::CoreExt::Hash::KeysSorter#initialize
      - Darthjee::CoreExt::Hash::DeepHashConstructor#initialize
      - Darthjee::CoreExt::Hash::DeepHashConstructor::Setter#initialize
      - Darthjee::CoreExt::Hash::Squasher#initialize
      - Darthjee::CoreExt::Hash::ValueChanger#initialize
  Summary::Presence:
    enabled: true
    exclude:
      - Darthjee::CoreExt::Hash::KeyChanger#initialize
      - Darthjee::CoreExt::Array::HashBuilder#initialize
      - Darthjee::CoreExt::Hash::ChainFetcher#initialize
      - Darthjee::CoreExt::Hash::ValueChanger#initialize
      - Darthjee::CoreExt::Hash::DeepHashConstructor#initialize
      - Darthjee::CoreExt::Hash::DeepHashConstructor::Setter#initialize
      - Darthjee::CoreExt::Hash::KeysSorter#initialize
      - Darthjee::CoreExt::Hash::Squasher#initialize
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
